### ISSUE TITLE
Supabase上にDBを作成する

### ISSUE THREAD

**Issue by shogyomujo11** [Shuheitkhs/teamsdev_16_2#25]
テーブル定義書通りのデータベースをSupabaseに作成してください。
Supabaseはご自身のアカウントで新規登録してください。無料枠で大丈夫です。
初期の動作確認用にダミーデータを2、3個入れておいてください。
一通りできたら他のチームメンバーを招待してください。

【ゴール】
Supabase上のダッシュボードでデータベースの中身が見られる。
テーブル定義書通りのテーブルが作られている。

【参考サイト】
テーブル定義書
https://www.figma.com/board/ahrYNBWFON2rr9Eop2h2N4/%E3%83%86%E3%83%BC%E3%83%96%E3%83%AB%E5%AE%9A%E7%BE%A9%E6%9B%B8%2FER%E5%9B%B3?node-id=0-1&node-type=canvas

Supabaseにデータベースを作る
https://qiita.com/pikimaru/items/5e51d36250c288b8b6dc

Supabaseにメンバーを招待する
https://zenn.dev/joo_hashi/articles/83043697718ead

**Comment by Shuheitkhs** [comment]
- supabaseのテーブル作成
- ダミーデータの入力
- チームメンバー招待

上記完了しました。

- あとはAPI keyなどの設定
- Prismaなどの導入

など考えられますが、一旦ここで報告します。

**Comment by Shuheitkhs** [comment]
チームメンバー全員がsupabaseのプロジェクトに参加しました。
