### ISSUE TITLE
BlogView画面の詳細設計レビュー

### ISSUE THREAD

**Issue by reoroi** [Shuheitkhs/teamsdev_16_2#39]
# 概要
BlogViewの画面詳細設計のレビュー内容

# 気になること

1. アクション一覧のA-02で文字数チェックするところが、C-02の入力値ではなくC-01のコメント入力値をチェックするのではないのでしょうか。

1. 投稿したコメント一覧はどう表示するのでしょうか。テーブル定義書のcommentsにpost_idがあるのでpost_idを使いブログ事のコメントを表示させるのではないでしょうか。

1. More Posts部分C-07とC-08にあたると思いますが、関連画像と関連タイトルとは何でしょうか。投稿主のほかの投稿をランダムで表示させるということですか。それとも同じカテゴリのpostsを表示させるのでしょうか。

**Comment by Shuheitkhs** [comment]
1.C-01の入力値なので書き換えておきます。
2.その想定です。書き加えておきます。
3.同じカテゴリの投稿で考えています。
