### ISSUE TITLE
【レビュー】Profile画面詳細設計

### ISSUE THREAD

**Issue by Shuheitkhs** [Shuheitkhs/teamsdev_16_2#65]
# 問題ないもの

- 画面概要
- コンポーネント一覧
- アクション一覧

# 気になるところ

> 下記取得条件に沿ってusersテーブルからレコードを取得する。

ここはpostsテーブルから、現在ログインしているユーザーのidと、postsテーブルのuser_idと一致するレコードを取得するが正しいかと思います。

> C-03: posts.created_at , upcreated_at

こちら「upcreated_at」は誤入力ですか？updated_atは必要でしょうか？

**Comment by you2626** [comment]
ご確認いただきありがとうございます！

[下記取得条件に沿ってusersテーブルからレコードを取得する。]
ここはpostsテーブルから、現在ログインしているユーザーのidと、postsテーブルのuser_idと一致するレコードを取得するが正しいかと思います。

→ご指摘の通り変更させていただきました。

[C-03: posts.created_at , upcreated_at]
こちら「upcreated_at」は誤入力ですか？updated_atは必要でしょうか？

→設計図では一つだけ日付を表示させておりましたので、投稿時は「created_at」を表示させて、更新されたら「updated_at」を表示させるようにと記載するつもりでした。

その他に「C-03: posts.category_id」「C-04: posts.user_id」が不足しておりましたので追加しました。
お手数ですが、よろしくお願いします。
