### ISSUE TITLE
11/15~11/21 進捗報告

### ISSUE THREAD

**Issue by shogyomujo11** [Shuheitkhs/teamsdev_16_2#78]
`報告内容`
- 自身のタスクの進捗度
- 現在詰まっている箇所やチームメンバーに共有しておきたいこと

`報告期限`
11月22日 定期ミーティング開始まで

**Comment by Shuheitkhs** [comment]
# 自身のタスクの進捗度

- blog_viewに関しての機能面（100%）
- スタイリング、リファクタリング（40%）
- commentコンポーネントとmorePostコンポーネントを作成したい

# 現在詰まっている箇所やチームメンバーに共有しておきたいこと

**Comment by reoroi** [comment]
自身のタスクの進捗度
write_viewのバリデーション
現在詰まっている箇所やチームメンバーに共有しておきたいこと

**Comment by you2626** [comment]
# 自身のタスクの進捗度

home画面、profile画面
・画像表示の伸縮
・content表示の字数制限

home画面
・せっかくコンポーネントがあるので、ページネーションはしたい

**Comment by hisanori-ito** [comment]
## 自身のタスクの進捗度
- プルリクのコメント対応

## 現在詰まっている箇所やチームメンバーに共有しておきたいこと
